### PR TITLE
Fix `SeStringReadOnlySpan.ToString` and add `SeStringBuilder.AppendMacroString`

### PR DESCRIPTION
**Pull request by Soreepeong**
* SeString.ToMacroString: Escape also `\` if the string is not being used as a string expression; otherwise, escape any of `[]()<>,\`.
* ReadOnlySeString/Payload/ExpressionSpan: Made it consistent with ToMacroString.

@pohky Mind testing this one?

### CODE REVIEW

**Comment by Soreepeong** [comment]
Added `SeStringBuilder.AppendMacroString`, and tested against all string columns in all sheets of all languages by doing what essentially is
```cs
ToReadOnlySeString == new SeStringBuilder().AppendMacroString(ToReadOnlySeString.ToString()).ToReadOnlySeString()
```
excluding subrow sheets as reading strings from subrow sheets wasn't functional.

**Comment by NotAdam** [comment]
can you fix the tests?

**Comment by Soreepeong** [comment]
Done! I was playing around with making `SeStringRenderer.InterpolatedStringHandler` also support encoding payloads and expressions using `...{MacroCode.If}{0}{1}{2}{MacroCode.Invalid}...` and the forgot to clean up after deciding that it's probably not a good idea.

**Review by NotAdam — APPROVED** [review]

**Comment by NotAdam** [comment]
cool, looks good to me - anything more you want to throw in or all good?

**Comment by Soreepeong** [comment]
Just added friendly error message and I think I'm done!

```
Unsupported MacroCode: "STRING" at 141 (byte offset at 282); "...33000011112222333300001111222233330000111122223333<string(bbbb<" ^^^^^ "STRING(ccc)>>AAAABBBBCCCCDDDDAAAABBBBCCCCDDDDAAAABBBBCCCCDDDDAAAA..."
```

**Pull request merged**
