### PR TITLE
Fix GetPageForRow

### PR DESCRIPTION
**Pull request by lmcintyre**

### CODE REVIEW

**Comment by NotAdam** [comment]
fixed this slightly differently
https://github.com/NotAdam/Lumina/commit/48c15e2701252dc040f21d9141e6fde615513881#diff-b675cac57663ddd512e11d027a43c36d8531cdd9930db128584dec1b24e14e4dR157-R161

**Comment by NotAdam** [comment]
tagged too, so should be good. back 2 spiderman 😎

**Comment by lmcintyre** [comment]
>:( my lazyrow fix

**Comment by NotAdam** [comment]
i didnt read the code LMAO

**Pull request merged**
