### PR TITLE
Make adjustments to bitfield generation

### PR DESCRIPTION
**Pull request by akuseru**
so this is nasty AF.
But I think this fixes up the bitfield generation issues. 

fixes:
bit-fields as arrays. 
multiple fields sharing the same bitfield.

There might be some bugs with it, as I am still working through validating data but it looks correct.

### CODE REVIEW

**Comment by NotAdam** [comment]
All the code in there is disgusting, mostly because of how irritating the SaintCoinach schema is to deal with, so no hard feelings if the code is hot trash lol

I ran this on a few sheets to give it a go and I couldn't find an example where the bitfields were an array, can you name one I can have a look at? But multiple fields sharing the same bitfield was intentional. with this PR, you're storing a bool for each bit and also keeping the original bitfield around too, which is a bit redundant once you've read the bits individually.

I would prefer that a single bitfield is still stored in 1 byte rather than 9 bytes, because that does add up pretty quickly too in terms of memory usage and it's more 'accurate' to how the data actually behaves too, if that makes sense. Happy to change approach if you have a better reason for doing it that way, but it just seems kind of wasteful to me

**Comment by akuseru** [comment]
https://github.com/ufx/SaintCoinach/pull/327/files#diff-a652c6fcc76d19d6539350975f79b928R356-R418

I was testing it against this pull request. These fields are what gave me quite a few issues, I don't know if the data here is even correct, but wanted to dig into it some. 

All the `& 0x1` values are under the `VisibleBool` column. all the `&0x2` values are under the ConditionBool column etc. 

Exporting became a pain because all the definitions ended up under the `visibleBool` column definition. 

 >  with this PR, you're storing a bool for each bit and also keeping the original bitfield around too, which is a bit redundant once you've read the bits individually.

Correct. I wanted the original values to be visible so that I could validate the values, but does not have to be visible, and can probably be removed to prevent confusion.

**Comment by NotAdam** [comment]
SC defs are sequential though, so VisibleBool would be `VisibleBool[0-7] & ( 1 << 0..7 )`? and so on? `& 0x2` would always be a part of the same bitset array

Unless that's what you fixed and I'm misreading?

**Comment by akuseru** [comment]
In sc: image

In the generated code:

```C#
 VisibleBool[61] = ( packed573 & 0x1 ) == 0x1;
            packed583 = parser.ReadOffset< byte >( 0x583, ExcelColumnDataType.UInt8 );

            VisibleBool[62] = ( packed583 & 0x1 ) == 0x1;
            packed593 = parser.ReadOffset< byte >( 0x593, ExcelColumnDataType.UInt8 );

            VisibleBool[63] = ( packed593 & 0x1 ) == 0x1;
            ConditionBool = new bool[64];
            ConditionBool[0] = ( packed1a3 & 0x2 ) == 0x2;
            ConditionBool[1] = ( packed1b3 & 0x2 ) == 0x2;
            ConditionBool[2] = ( packed1c3 & 0x2 ) == 0x2;
```

which lines up with SC. 

I was simply commenting on how it was annoying how a lot of these columns ended up as children of the VisibleBool column grouping instead of creating their own `GeneratedColumnDef` type.

**Comment by NotAdam** [comment]
Ah, right, I get what you mean. Sounds good to me, at this point I'll probably take something that works a bit better over something that doesn't, but the only way to fix this mess is to clean up the SC defs and that's a huge amount of work, especially for all the nested groups too that realistically should be nested structs.

Let me know if you want to generate new defs and PR those, I can make a new release afterwards with those included otherwise I'll just make one containing the previous fix

**Pull request merged**
