### PR TITLE
Add LINQ FirstOrNull/TryGetFirst extensions

### PR DESCRIPTION
**Pull request by WorkingRobot**

### CODE REVIEW

**Comment by NotAdam** [comment]
i'm actually confused, how is this not equal to FirstOrDefault?

**Comment by nebel** [comment]
> i'm actually confused, how is this not equal to FirstOrDefault?

The `default` of a struct is not null, but a struct with all fields with their `default` values.

**Comment by NotAdam** [comment]
ahhhh yep, was thinking it was all classes for some reason

**Review by NotAdam — APPROVED** [review]

**Comment by NotAdam** [comment]
first would throw an exception if there's no elements, and firstordefault would have the same side effect of a default struct, so its the same reasoning for both

**Comment by NotAdam** [comment]
I was trying to think actually why they're structs and not classes and I can't think of a compelling reason but that would break pretty much everything to change so whatever lol

**Pull request merged**
